import { createHash,randomUUID } from "node:crypto";import { mkdir,writeFile } from "node:fs/promises";import { resolve } from "node:path";import { expect,test } from "@playwright/test";
const evidence=resolve(process.cwd(),"../../docs/test-evidence");
test("complete offline-ready MVP workflow",async({page,context})=>{await mkdir(evidence,{recursive:true});await context.route("**/*",route=>{const url=new URL(route.request().url());if(url.hostname==="127.0.0.1"||url.hostname==="localhost")return route.continue();return route.abort("internetdisconnected")});
await page.goto("/login");await page.getByLabel("Username").fill("admin");await page.getByLabel("Password").fill("Admin123!Quest");await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL(/\/queue/);
const patientId=`E2E-${randomUUID().slice(0,8).toUpperCase()}`;await page.getByRole("link",{name:"Patients"}).click();await page.getByLabel("Patient ID").fill(patientId);await page.getByLabel("First name").fill("Maya");await page.getByLabel("Middle name").fill("Reyes");await page.getByLabel("Last name").fill("Santos");await page.getByLabel("Date of birth").fill("1992-04-18");await page.getByLabel("Sex").selectOption("FEMALE");await page.getByLabel("Phone").fill("09171234567");await page.getByLabel("Address").fill("Quezon City");await page.getByRole("button",{name:"Register patient"}).click();await expect(page.getByText(`Patient ${patientId} registered.`)).toBeVisible();
await page.getByRole("link",{name:"New order"}).click();await page.getByPlaceholder("Search patient ID or name").fill(patientId);await page.getByRole("button",{name:new RegExp(patientId)}).click();await page.getByLabel("Priority").selectOption("ROUTINE");await page.getByPlaceholder("Dr. Ana Cruz").fill("Dr. Ana Cruz");await page.getByPlaceholder("Walk-in").fill("Walk-in");await page.getByRole("checkbox",{name:/GLU Glucose/}).check();await page.getByRole("button",{name:"Create order & accession"}).click();await expect(page).toHaveURL(/\/results\//);await page.getByLabel("GLU result").fill("126");await page.getByRole("button",{name:"Save draft"}).click();await expect(page.getByText(/Current state: ENTERED/)).toBeVisible();await page.getByRole("button",{name:"Submit for validation"}).click();await expect(page.getByText(/Current state: FOR VALIDATION/)).toBeVisible();await page.getByRole("button",{name:"Validate"}).click();await expect(page.getByText(/Current state: VALIDATED/)).toBeVisible();await page.getByRole("button",{name:"Release & create PDF"}).click();await expect(page.getByRole("link",{name:"Open final PDF"})).toBeVisible();
await page.screenshot({path:resolve(evidence,"released-result-workflow.png"),fullPage:true});const reportHref=await page.getByRole("link",{name:"Open final PDF"}).getAttribute("href");const report=await page.request.get(reportHref!);expect(report.ok()).toBeTruthy();const reportBytes=await report.body();expect(reportBytes.subarray(0,4).toString()).toBe("%PDF");await writeFile(resolve(evidence,"sample-final-result-report.pdf"),reportBytes);
const rawPayload="SIM|QC20990101-9999|GLU|99";await page.request.post("/api/gateway/v1/messages",{headers:{authorization:"Bearer questcare-mvp-local-gateway-secret-change-me"},data:{schemaVersion:"1.0",gatewayMessageId:randomUUID(),gatewayId:"gateway-e2e",connectionId:"SIM-01",adapter:{type:"simulator",version:"1.0.0"},occurredAt:new Date().toISOString(),receivedAt:new Date().toISOString(),idempotencyKey:createHash("sha256").update(randomUUID()).digest("hex"),rawSha256:createHash("sha256").update(rawPayload).digest("hex"),rawEncoding:"UTF-8",rawPayload,accessionId:"QC20990101-9999",results:[{itemIndex:0,analyzerTestCode:"GLU",valueType:"NUMERIC",value:"99",unit:"mg/dL",flags:[]}]}});await page.goto("/analyzers");await expect(page.getByText("UNKNOWN ACCESSION").first()).toBeVisible();await page.screenshot({path:resolve(evidence,"analyzer-exception-dashboard.png"),fullPage:true});
});
